# Generated by Django 5.0.1 on 2024-02-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_tbl_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_place',
            name='pincode',
            field=models.CharField(default=67, max_length=50),
            preserve_default=False,
        ),
    ]
