# Generated by Django 5.0.1 on 2024-02-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_place_pincode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_place',
        ),
    ]
