# Generated by Django 5.0.2 on 2024-02-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_place',
        ),
    ]
