# Generated by Django 5.0.2 on 2024-02-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_donationtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donationtype_name', models.CharField(max_length=50)),
            ],
        ),
    ]
