# Generated by Django 5.0.2 on 2024-02-15 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_place'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_orphanage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orphanage_name', models.CharField(max_length=50)),
                ('orphanage_contact', models.CharField(max_length=50)),
                ('orphanage_email', models.CharField(max_length=50)),
                ('orphanage_password', models.CharField(max_length=50)),
                ('orphanage_photo', models.FileField(upload_to='Assets/UserPhoto/')),
                ('orphanage_proof', models.FileField(upload_to='Assets/UserProof/')),
                ('orphanage_status', models.IntegerField(default='0')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
