# Generated by Django 5.0.2 on 2024-02-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_orphanage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
