# Generated by Django 5.0.2 on 2024-04-09 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_orphanage_orphanage_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.CharField(max_length=500)),
                ('chat_time', models.DateTimeField()),
                ('chat_file', models.FileField(upload_to='ChatFiles/')),
                ('orphnage_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orphnage_from', to='Guest.tbl_orphanage')),
                ('orphnage_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orphnage_to', to='Guest.tbl_orphanage')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='Guest.tbl_user')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='Guest.tbl_user')),
            ],
        ),
    ]
