# Generated by Django 5.0.2 on 2024-04-09 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_tbl_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_chat',
            name='orphnage_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orphnage_from', to='Guest.tbl_orphanage'),
        ),
        migrations.AlterField(
            model_name='tbl_chat',
            name='orphnage_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orphnage_to', to='Guest.tbl_orphanage'),
        ),
        migrations.AlterField(
            model_name='tbl_chat',
            name='user_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='Guest.tbl_user'),
        ),
        migrations.AlterField(
            model_name='tbl_chat',
            name='user_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='Guest.tbl_user'),
        ),
    ]
