# Generated by Django 5.0.2 on 2024-03-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orphanage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_request',
        ),
    ]
