# Generated by Django 5.0.1 on 2024-04-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orphanage', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_request',
            name='request_count',
        ),
    ]
